[package]
name = "counter-doom"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3


[dependencies]
avian2d = "0.2.1"
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
rand = "0.9.0"
